FROM golang:1.16.4 AS build
LABEL quay.expires-after=1h

USER root

ADD restserver /temp/
WORKDIR /temp
RUN CGO_ENABLED=1 go build -tags netgo -a -v

FROM alpine:3.14
LABEL quay.expires-after=27w

USER root

COPY --from=build /temp/restserver /usr/local/bin

EXPOSE 1323

ENTRYPOINT ["restserver"]